use_frameworks!
platform :ios, '8.0'
target 'CDDevUtility_Example' do
  pod 'CDDevUtility', :path => '../'

  target 'CDDevUtility_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    
    pod 'Expecta+Snapshots'
  end
end
