use_frameworks!

target 'CDDevUtility_Example' do
  pod 'CDDevUtility', :path => '../'

  target 'CDDevUtility_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
